apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON {{ .Values.database.name }}.* TO '{{ .Values.database.user }}'@'%';
    USE {{ .Values.database.name }};
    CREATE TABLE counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );
