apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
  namespace: {{ .Values.common.namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.pv.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/{{ .Chart.Name }}"
